# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -ldflags="-s -w" -v ./cmd/qrank-builder
        upx qrank-builder
        go build -ldflags="-s -w" -v ./cmd/webserver
        upx webserver
        go build -ldflags="-s -w" -v ./cmd/osmviews-builder
        upx osmviews-builder

    - name: Test
      run: go test -v ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qrank
        path: qrank-builder
        retention-days: 7
